#!/usr/bin/env python3
"""
MicroHs Profiling Data Analysis Tool

Analyzes the profiling data generated by MicroHs runtime with -profile flag.
Provides insights into combinator usage patterns and suggests JIT optimization targets.
"""

import sys
import re
from collections import defaultdict, Counter
import argparse

def parse_profile_data(filename):
    """Parse the mhs-profile.txt file"""
    combinator_counts = {}
    bigram_patterns = []
    
    with open(filename, 'r') as f:
        content = f.read()
    
    # Parse combinator counts
    counts_section = re.search(r'COMBINATOR_COUNTS:\s*(.*?)\n\nBIGRAM_PATTERNS:', 
                              content, re.DOTALL)
    if counts_section:
        for line in counts_section.group(1).strip().split('\n'):
            if ':' in line:
                name, count = line.split(':', 1)
                combinator_counts[name.strip()] = int(count.strip())
    
    # Parse bigram patterns  
    bigrams_section = re.search(r'BIGRAM_PATTERNS:\s*(.*?)$', content, re.DOTALL)
    if bigrams_section:
        for line in bigrams_section.group(1).strip().split('\n'):
            if ' -> ' in line and ':' in line:
                pattern, count = line.rsplit(':', 1)
                first, second = pattern.split(' -> ', 1)
                bigram_patterns.append((first.strip(), second.strip(), int(count.strip())))
    
    return combinator_counts, bigram_patterns

def analyze_hot_combinators(combinator_counts, top_n=10):
    """Identify the most frequently executed combinators"""
    sorted_combinators = sorted(combinator_counts.items(), key=lambda x: x[1], reverse=True)
    total_executions = sum(combinator_counts.values())
    
    print(f"## Hot Combinators Analysis (Top {top_n})")
    print(f"Total combinator executions: {total_executions:,}")
    print()
    
    cumulative_percent = 0
    for i, (name, count) in enumerate(sorted_combinators[:top_n]):
        percent = (count / total_executions) * 100
        cumulative_percent += percent
        print(f"{i+1:2}. {name:12} {count:>12,} ({percent:5.1f}%) [cum: {cumulative_percent:5.1f}%]")
    
    print()
    # Identify JIT compilation candidates
    hot_threshold = total_executions * 0.01  # 1% threshold
    jit_candidates = [name for name, count in sorted_combinators if count >= hot_threshold]
    
    print(f"## JIT Compilation Candidates (>{hot_threshold:,.0f} executions)")
    for name in jit_candidates[:15]:  # Top 15 candidates
        count = combinator_counts[name]
        percent = (count / total_executions) * 100
        print(f"  {name:12} {count:>12,} ({percent:5.1f}%)")
    print()
    
    return jit_candidates

def analyze_bigram_patterns(bigram_patterns, top_n=15):
    """Analyze combinator sequence patterns"""
    print(f"## Bigram Patterns Analysis (Top {top_n})")
    print("These show common combinator execution sequences for fusion opportunities:")
    print()
    
    total_bigrams = sum(count for _, _, count in bigram_patterns)
    
    for i, (first, second, count) in enumerate(bigram_patterns[:top_n]):
        percent = (count / total_bigrams) * 100 if total_bigrams > 0 else 0
        print(f"{i+1:2}. {first:12} -> {second:12} {count:>8,} ({percent:5.1f}%)")
    
    print()
    # Identify fusion candidates
    fusion_candidates = []
    for first, second, count in bigram_patterns[:20]:
        if count >= total_bigrams * 0.005:  # 0.5% threshold
            fusion_candidates.append((first, second, count))
    
    print(f"## Combinator Fusion Candidates")
    print("High-frequency patterns suitable for single native instruction sequences:")
    print()
    for first, second, count in fusion_candidates:
        percent = (count / total_bigrams) * 100
        print(f"  {first} -> {second:12} {count:>8,} ({percent:5.1f}%)")
    print()

def analyze_combinator_types(combinator_counts):
    """Categorize combinators by type for targeted optimization"""
    categories = {
        'Basic Combinators': ['S', 'K', 'I', 'B', 'C', 'A', 'Y', 'U', 'P', 'R', 'O'],
        'Extended Combinators': ['SS', 'BB', 'CC', 'K2', 'K3', 'K4', 'Z', 'J'],
        'Arithmetic': ['ADD', 'SUB', 'MUL', 'QUOT', 'REM', 'NEG'],
        'Comparison': ['EQ', 'NE', 'LT', 'LE', 'GT', 'GE'], 
        'Bitwise': ['AND', 'OR', 'XOR', 'INV', 'SHL', 'SHR'],
        'Data Types': ['INT', 'DBL', 'FLT32', 'PTR', 'AP'],
        'I/O Operations': [c for c in combinator_counts.keys() if c.startswith('T_IO_')],
        'Other': []
    }
    
    categorized = defaultdict(int)
    uncategorized = set(combinator_counts.keys())
    
    for category, combinators in categories.items():
        if category == 'Other':
            continue
        for comb in combinators:
            if comb in combinator_counts:
                categorized[category] += combinator_counts[comb] 
                uncategorized.discard(comb)
            # Also check for variations with T_ prefix
            t_comb = f'T_{comb}'
            if t_comb in combinator_counts:
                categorized[category] += combinator_counts[t_comb]
                uncategorized.discard(t_comb)
    
    # Put remaining in 'Other'
    for comb in uncategorized:
        categorized['Other'] += combinator_counts[comb]
    
    total = sum(categorized.values())
    print("## Combinator Categories Analysis")
    print("Distribution of execution by combinator type:")
    print()
    
    sorted_categories = sorted(categorized.items(), key=lambda x: x[1], reverse=True)
    for category, count in sorted_categories:
        if count > 0:
            percent = (count / total) * 100
            print(f"  {category:20} {count:>12,} ({percent:5.1f}%)")
    print()

def generate_jit_recommendations(combinator_counts, bigram_patterns):
    """Generate specific JIT implementation recommendations"""
    total_executions = sum(combinator_counts.values())
    hot_threshold = total_executions * 0.005  # 0.5% threshold
    
    print("## JIT Implementation Recommendations")
    print()
    
    # Phase 1 recommendations
    phase1 = []
    for name, count in combinator_counts.items():
        if count >= hot_threshold:
            if name in ['I', 'K', 'A', 'ADD', 'SUB', 'MUL']:
                phase1.append((name, count))
    
    phase1.sort(key=lambda x: x[1], reverse=True)
    
    print("### Phase 1: High-Impact Simple Optimizations")
    for name, count in phase1[:8]:
        percent = (count / total_executions) * 100
        print(f"  - {name:8} {count:>10,} executions ({percent:4.1f}%) - Eliminate switch dispatch")
    
    # Phase 2 recommendations  
    print("\n### Phase 2: Combinator Fusion Opportunities")
    fusion_threshold = sum(count for _, _, count in bigram_patterns) * 0.01
    fusion_ops = [(f, s, c) for f, s, c in bigram_patterns[:10] if c >= fusion_threshold]
    
    for first, second, count in fusion_ops:
        print(f"  - {first} -> {second}: {count:>8,} occurrences - Fuse into single operation")
    
    # Phase 3 recommendations
    print("\n### Phase 3: Specialized Code Generation")
    arithmetic = ['ADD', 'SUB', 'MUL', 'QUOT', 'T_ADD', 'T_SUB', 'T_MUL']
    arith_total = sum(combinator_counts.get(op, 0) for op in arithmetic)
    if arith_total > hot_threshold * 2:
        print(f"  - Arithmetic operations: {arith_total:,} total - Generate native CPU instructions")
    
    comparison = ['EQ', 'NE', 'LT', 'LE', 'GT', 'GE', 'T_EQ', 'T_NE', 'T_LT', 'T_LE', 'T_GT', 'T_GE']
    comp_total = sum(combinator_counts.get(op, 0) for op in comparison)
    if comp_total > hot_threshold * 2:
        print(f"  - Comparison operations: {comp_total:,} total - Optimize branching patterns")
    print()

def main():
    parser = argparse.ArgumentParser(description='Analyze MicroHs profiling data')
    parser.add_argument('profile_file', nargs='?', default='mhs-profile.txt',
                       help='Path to profile data file (default: mhs-profile.txt)')
    parser.add_argument('--top', type=int, default=10,
                       help='Number of top items to show (default: 10)')
    parser.add_argument('--bigrams', type=int, default=15, 
                       help='Number of top bigrams to show (default: 15)')
    args = parser.parse_args()
    
    try:
        combinator_counts, bigram_patterns = parse_profile_data(args.profile_file)
    except FileNotFoundError:
        print(f"Error: Profile file '{args.profile_file}' not found.")
        print("Run MicroHs with +RTS -profile -RTS to generate profiling data.")
        sys.exit(1)
    except Exception as e:
        print(f"Error parsing profile data: {e}")
        sys.exit(1)
    
    if not combinator_counts:
        print("No profiling data found. Make sure to run with +RTS -profile -RTS")
        sys.exit(1)
    
    print("# MicroHs Profiling Analysis Report")
    print("=" * 50)
    print()
    
    # Main analyses
    jit_candidates = analyze_hot_combinators(combinator_counts, args.top)
    analyze_bigram_patterns(bigram_patterns, args.bigrams)
    analyze_combinator_types(combinator_counts)
    generate_jit_recommendations(combinator_counts, bigram_patterns)
    
    print(f"Analysis complete. Data from {args.profile_file}")

if __name__ == '__main__':
    main()